web/books/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, SearchResultsListView

app_name = "books"

urlpatterns = [
    path("", BookListView.as_view(), name="list"),
    path("<uuid:pk>/", BookDetailView.as_view(), name="detail"),
    path("search/", SearchResultsListView.as_view(), name="search_results"),
]

web/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('books/', include('books.urls')),
]

if not settings.S3: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]

web/pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView


urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("about", AboutPageView.as_view(), name="about"),
]

web/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    def __str__(self):
        return self.email

web/books/models.py
import uuid
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Book(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    cover = models.ImageField(upload_to="covers/", blank=True)

    class Meta:
        verbose_name = "Book"
        verbose_name_plural = "Books"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:detail", args=[str(self.id)])


class Review(models.Model):
    book = models.ForeignKey(
        "books.Book", on_delete=models.CASCADE, related_name="reviews"
    )
    content = models.CharField(max_length=255)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.content

web/pages/models.py
from django.db import models

# Create your models here.

web/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
        )

web/accounts/views.py
from django.shortcuts import render

# Create your views here.

web/books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.db.models import Q
from .models import Book


class BookListView(ListView):
    model = Book
    template_name = "books/list.html"
    context_object_name = "books"
    login_url = "account_login"


class BookDetailView(DetailView):
    model = Book
    template_name = "books/detail.html"
    context_object_name = "book"


class SearchResultsListView(ListView):
    model = Book
    context_object_name = "books"
    template_name = "books/search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")

        return Book.objects.filter(
            Q(title__icontains=query) | Q(author__icontains=query)
        )

web/pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "pages/index.html"


class AboutPageView(TemplateView):
    template_name = "pages/about.html"

templates/books/list.html
{% extends "_base.html" %}

{% block title %}{{ block.super}} - Books{% endblock  %}

{% block content %}
    {% for book in books %}
        <div>
            <h2 class="title"><a href="{{ book.get_absolute_url }}" class="is-link">{{ book.title }}</a></h2>
        </div>
    {% endfor %}
{% endblock  %}

web/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="light">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>
      {% block title %}
        Django Meta
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  </head>
  <body>
    {% comment %}Navbar{% endcomment %}
    <nav class="navbar is-primary has-shadow" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'index' %}"><h2 class="is-size-3">Django Meta</h2></a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item is-size-4" href="{% url 'index' %}">Home</a>
          <a class="navbar-item is-size-4" href="{% url 'books:list' %}">Books</a>
          <a class="navbar-item is-size-4" href="{% url 'about' %}">About</a>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              {% if user.is_authenticated %}
                <div class="dropdown is-hoverable">
                  <div class="dropdown-trigger">
                    <button class="button mx-2 is-primary" aria-haspopup="true" aria-controls="dropdown-menu4">
                      <span>{{ user.email }}</span>
                      <span class="icon is-small"><i class="fas fa-regular fa-user"></i></span>
                    </button>
                  </div>
                  <div class="dropdown-menu" id="dropdown-menu4" role="menu">
                    <div class="dropdown-content ml-2">
                      <div class="dropdown-item has-text-centered p-0">
                        <a href="{% url 'account_change_password' %}">Change Password</a>
                      </div>
                      {% if user.is_superuser %}
                        <div class="dropdown-item has-text-centered p-0">
                          <a href="/admin">Admin</a>
                        </div>
                      {% endif %}
                    </div>
                  </div>
                </div>
                <a class="button is-dark" href="{% url 'account_logout' %}"><strong>Logout</strong></a>
              {% else %}
                <a class="button is-dark" href="{% url 'account_signup' %}"><strong>Sign up</strong></a>
                <a class="button is-light" href="{% url 'account_login' %}">Log in</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    {% block hero %}

    {% endblock %}
    {% include '_messages.html' %}
    <div class="container is-fluid">
      {% block content %}

      {% endblock %}
    </div>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="https://kit.fontawesome.com/b0db48a491.js" crossorigin="anonymous"></script>
  </body>
</html>

web/templates/_messages.html
{% if messages %}
  <div class="messages m-0">
    {% for message in messages %}
      <div class="notification {% if message.tags %}is-{{ message.tags }}{% endif %}">
        <button class="delete"></button>
        {{ message }}
      </div>
    {% endfor %}
  </div>
{% endif %}

web/templates/books/detail.html
{% extends '_base.html' %}

{% block title %}
  {{ book.title }}
{% endblock %}

{% block content %}
  <div class="columns is-mobile">
    <div class="column is-half-tablet is-offset-one-quarter-tablet">
      <div class="card my-3">
        <div class="card-image">
          <figure class="image is-3by4">
            {% if book.cover %}
              <img src="{{ book.cover.url }}" alt="{{ book.title }}" />
            {% else %}
              <img src="https://bulma.io/assets/images/placeholders/320x480.png" />
            {% endif %}
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-content has-text-centered">
              <p class="title is-4">{{ book.title }}</p>
              <p class="subtitle is-6">{{ book.author }}</p>
              <p class="subtitle is-6">${{ book.price }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="review-container mb-5">
    <h2 class="title has-text-centered">Reviews</h2>
    {% for review in book.reviews.all %}
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p>
                <strong>{{ review.author.email }}</strong>
                <br />
                <p>{{ review.content }}</p>
              </p>
            </div>
          </div>
        </article>
      </div>
      {% empty %}
      <p class="has-text-centered">There are no reviews.</p>
    {% endfor %}
  </div>
{% endblock %}

web/templates/books/list.html
{% extends "_base.html" %}

{% block title %}{{ block.super}} - Search Results{% endblock  %}

{% block content %}
    {% for book in books %}
        <div>
            <h2 class="title"><a href="{{ book.get_absolute_url }}" class="is-link">{{ book.title }}</a></h2>
        </div>
    {% endfor %}
{% endblock  %}

web/templates/books/search_results.html
{% extends '_base.html' %}

{% block title %}
  {{ block.super }} - Search Results
{% endblock %}

{% block content %}
  <h2 class="title has-text-centered">Search Results</h2>
  {% for book in books %}
    <div>
      <h2 class="title"><a href="{{ book.get_absolute_url }}" class="is-link">{{ book.title }}</a></h2>
    </div>
    {% empty %}
    <p>There are no results.</p>
  {% endfor %}
{% endblock %}

web/templates/pages/about.html
{% extends '_base.html' %}

{% block content %}
<h2 class="has-text-centered title my-2">About Page</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo officiis distinctio expedita nemo et officia corporis repellendus excepturi sapiente magni itaque, nam sed provident maiores fugit adipisci, omnis, eaque cumque!</p>
{% endblock %}

web/templates/pages/index.html
{% extends '_base.html' %}

{% block content %}
<form action="/books/search" method="get" class="my-3">
  <div class="field has-addons">
    <div class="control">
      <input class="input" type="text" name="q" required placeholder="Find a book" />
    </div>
    <div class="control">
      <button class="button is-info">Search</button>
    </div>
  </div>
</form>
  {% if user.is_authenticated %}
    Hello {{ user.email }}!<p>
      <a href="{% url 'account_logout' %}">Log Out</a>
    </p>
  {% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'account_login' %}">Log In</a>
    <a href="{% url 'account_signup' %}">Sign Up</a>
  {% endif %}
{% endblock %}